clc; clear all; close all

theta = linspace(0,720,20);
rho = 0.005*theta/10;
size_filled = randi(8, length(theta),1);
% sizes: random positive integer selected from 1~8
color_p = rand(length(theta),1);
% colors generated by rand()
figure(1)
theta_radians = deg2rad(theta);
polarscatter(theta_radians,rho,...
    100*size_filled,color_p,'filled',...
    'MarkerFaceAlpha',.5)